export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import "../styles/globals.css";
import Header from "@/components/Header/index.";

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <Header/>
        {children}
        </body>
    </html>
  )
}
