export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import Nav from "@/components/nav";
export default function loginLayout({ children }) {
  return (
    <div className="text-black">
      <Nav/>
      {children}
    </div>
  );
}
